/** Display-only Urdu for Course 2 TOC; keys match `app/course2/learn/page.tsx` COURSE2_TOC titles exactly. */
export const COURSE2_TOC_URDU: Record<string, string> = {
  "Introduction to Auto electrician basics": "آٹو الیکٹریشن کی بنیادیں",
  "Safety Precautions general and auto electrician shop Firefighting, First aid, Environmental protection, Reasons for workshop accidents Possible causes of accidents in workshop and their safety precautions":
    "حفاظتی احتیاطیں، فائر فائٹنگ، فرسٹ ایڈ، ماحولیات، ورکشاپ حادثات اور ان کی روک تھام",
  "Introduction to hand tools & equipment used in auto electrician":
    "آٹو الیکٹریشن میں استعمال ہونے والے ہینڈ ٹولز اور آلات",
  "Measuring tools (vernier caliper, feeler gauge)": "پیمائش کے اوزار (ورنیئر کالیپر، فیلر گیج)",
  "Introduction to Auto motive four stroke engine": "فور اسٹروک انجن کا تعارف",
  "Basic electricity. (Atomic structure of matter and electricity)":
    "بنیادی بجلی (مادہ اور بجلی کی ذراتی ساخت)",
  "Conductor, insulator, semi conductor": "چالک، موصل، نیم موصل",
  "Current, voltage and resistance": "کرنٹ، وولٹیج اور مزاحمت",
  "Ohm's law": "اوم کا قانون",
  "Symbols used in electrical wiring": "بجلی کی وائرنگ میں استعمال ہونے والے علامات",
  "Series and parallel circuits": "سیریز اور متوازی سرکٹ",
  "Electric circuit problems": "بجلی کے سرکٹ کے مسائل",
  "Magnet, magnetism and electromagnet": "میگنیٹ، مقناطیسیت اور الیکٹرو میگنیٹ",
  "Relays, solenoid, printed, circuits, circuit breaker, fuse, types of bulb, terminals and switches.":
    "ریلے، سولینائڈ، پرنٹڈ سرکٹ، سرکٹ بریکر، فیوز، بلب کی اقسام، ٹرمینل اور سوئچ",
  "Diodes and transistors": "ڈائیوڈز اور ٹرانزسٹرز",
  "PNP & NPN type semiconductor's": "PNP اور NPN قسم کے سیمی کنڈکٹر",
  Thermistor: "تھرمسٹر",
  "Logic Gates": "لاجک گیٹس",
  "Sensors and actuators": "سینسر اور ایکچویٹر",
  "Purpose, Construction and types of battery": "بیٹری کا مقصد، ساخت اور اقسام",
  "Charging and discharging of battery": "بیٹری چارج اور ڈسچارج",
  "Battery rating": "بیٹری ریٹنگ",
  "Starting System of Vehicle": "گاڑی کا سٹارٹنگ سسٹم",
  "Describe the Purpose, Principle and Construction of starter motor":
    "سٹارٹر موٹر کا مقصد، اصول اور ساخت",
  "Operation of solenoid switch and motor": "سولینائڈ سوئچ اور موٹر کا عمل",
  "Neutral safety switch": "نیوٹرل سیفٹی سوئچ",
  "Charging system of Vehicle": "گاڑی کا چارجنگ سسٹم",
  "Purpose, circuit diagram and Function of Charging Systems": "چارجنگ سسٹمز کا مقصد، سرکٹ ڈایاگرام اور کام",
  "Function, construction and operation of alternator": "الٹرنیٹر کا کام، ساخت اور عمل",
  "Construction and operation of double point voltage regulator":
    "ڈبل پوائنٹ وولٹیج ریگولیٹر کی ساخت اور عمل",
  "Electronic regulators": "الیکٹرانک ریگولیٹرز",
  "Ignition system of Vehicle": "گاڑی کا اگنیشن سسٹم",
  "Purpose & types of ignition system": "اگنیشن سسٹم کا مقصد اور اقسام",
  "Construction of conventional ignition system": "روایتی اگنیشن سسٹم کی ساخت",
  "Ignition switch, Ignition coil, Distributor, Spark plug and its types":
    "اگنیشن سوئچ، کوائل، ڈسٹریبیوٹر، سپارک پلگ اور اس کی اقسام",
  "Capacitor discharge ignition": "کیپیسٹر ڈسچارج اگنیشن",
  "Pickup coil type ignition": "پک اپ کوائل ٹائپ اگنیشن",
  "Multiple coil and distribute less ignition": "ملٹی کوائل اور ڈسٹریبیوٹر لیس اگنیشن",
  "Firing order": "فائرنگ آرڈر",
  "Ignition timing": "اگنیشن ٹائمنگ",
  "Wiring Circuits and Accessories": "وائرنگ سرکٹ اور لوازمات",
  "Purpose and construction of Horn circuit, Head lamps circuit, other lights":
    "ہارن، ہیڈ لیمپ اور دیگر لائٹس کے سرکٹ کا مقصد اور ساخت",
  "Wind shield wipers/washers circuit": "وائڈ شیلڈ وائپر/واشر سرکٹ",
  "Power windows": "پاور ونڈوز",
  "Electric power steering": "الیکٹرک پاور اسٹیئرنگ",
  "Instrument panel gauges, meters, indicators": "انسٹرومنٹ پینل گیج، میٹر، انڈیکیٹر",
  "Introduction to EFI system components (Sensors, ECM & Actuators)":
    "EFI سسٹم پرزوں کا تعارف (سینسر، ECM، ایکچویٹر)",
  "Introduction to electronic engine controls": "انجن الیکٹرانک کنٹرول کا تعارف",
  "Vehicle air conditioning and heating system": "گاڑی کا اے سی اور ہیٹنگ سسٹم",
  "Ventilating, Heating, Dehumidifying and Defrosting function of vehicle":
    "وینٹیلیشن، ہیٹنگ، نمی ختم اور ڈیفروسٹنگ",
  "Components & the working principle of Air conditioner(AC)": "اے سی کے پرزے اور اصول کار",
  "Working of thermostats switch & Compressor clutch of AC": "تھرمواسٹٹ سوئچ اور کمپریسر کلچ",
  "Gas charging of compressor": "کمپریسر میں گیس چارجنگ",
  "Automatic temperature control": "خودکار درجہ حرارت کنٹرول",
  "Trouble shooting its possible causes and their remedies of Heating system":
    "ھیٹنگ سسٹم میں خرابی، اسباب اور علاج",
  "Trouble shooting its possible causes and their remedies of Air conditioner":
    "اے سی میں خرابی، اسباب اور علاج",
  "Hybrid & Electric Vehicles": "ہائبرڈ اور الیکٹرک گاڑیاں",
  "Introduction to hybrid and electric vehicles": "ہائبرڈ اور الیکٹرک گاڑیوں کا تعارف",
  "Types of Hybrid systems": "ہائبرڈ سسٹمز کی اقسام",
  "Degree of hybridization": "ہائبرڈائزیشن کی سطح",
  "Charging system & Hybrid vehicle drive train": "چارجنگ اور ہائبرڈ ڈرائیو ٹرین",
  "Plug in hybrid and electric vehicles": "پلگ ان ہائبرڈ اور الیکٹرک گاڑیاں",
  "EURO emission standards": "یورو اخراج کے معیار",
  "Use of fire extinguisher": "فائر بجھانے والے آلہ کا استعمال",
  "Measurement with vernier caliper": "ورنیئر کالیپر سے پیمائش",
  "Measurement with wire gauge": "وائر گیج سے پیمائش",
  "Soldering (eye joint, lap joint, T Joint)": "سولڈرنگ (آئی، لیپ، ٹی جوائنٹ)",
  "Use of Multimeter": "ملٹی میٹر کا استعمال",
  "Crimp connecting": "کرمپ کنکشن",
  "Making test lamp": "ٹیسٹ لیمپ بنانا",
  "Studying characteristics of magnets": "میگنیٹ کی خصوصیات",
  "Interpret wiring diagram and color coding": "وائرنگ ڈایاگرام اور رنگ کوڈ",
  "Making Series and parallel circuits": "سیریز اور متوازی سرکٹ بنانا",
  "Check fuse, switch, diode, and transistor": "فیوز، سوئچ، ڈائیوڈ اور ٹرانزسٹر چیک",
  "Prepare full wave rectifier": "فل ویو ریکٹیفائر تیار کرنا",
  "Make Different Logic gate circuits": "لاجک گیٹ سرکٹ بنانا",
  "Checking different ICs": "مختلف ICs چیک کرنا",
  "Identify parts of four stroke engine Identification of battery parts":
    "فور اسٹروک انجن اور بیٹری پرزوں کی شناخت",
  "Cleaning and topping up": "صفائی اور ٹاپ اپ",
  "Checking specific gravity": "مخصوص کثافت چیک",
  "Battery charging": "بیٹری چارجنگ",
  "Preparation of electrolyte": "الیکٹرولائٹ کی تیاری",
  "Light load test": "لائٹ لوڈ ٹیسٹ",
  "Trouble shooting (under charging & overcharging)": "کم/زیادہ چارجنگ میں خرابی دور کرنا",
  "Wiring up starting circuit": "سٹارٹنگ سرکٹ وائرنگ",
  "Dismantling, checking of starter motor": "سٹارٹر موٹر کھولنا اور چیک",
  "Starter motor components, assembling, performance checking":
    "سٹارٹر پرزے، اسمبلی، کارکردگی ٹیسٹ",
  "Trouble shooting their possible causes and remedies of starting system":
    "سٹارٹنگ سسٹم میں خرابی اور علاج",
  "Wiring up Charging circuit on wiring board": "وائرنگ بورڈ پر چارجنگ سرکٹ",
  "Charging system inspection & diagnosing": "چارجنگ سسٹم معائنہ اور تشخیص",
  "Adjusting alternator belt tension": "الٹرنیٹر بیلٹ تناؤ",
  "dismantling, checking and inspection, assembling, of Alternator":
    "الٹرنیٹر کھولنا، چیک، اسمبلی",
  "Checking output of alternator": "الٹرنیٹر آؤٹ پٹ چیک",
  "Replacing carbon brush": "کاربن برش تبدیل",
  "Trouble shooting their possible causes and remedies of charging system":
    "چارجنگ سسٹم میں خرابی اور علاج",
  "Wiring of conventional ignition system": "روایتی اگنیشن وائرنگ",
  "Replacing C.B points": "سی بی پوائنٹس تبدیل",
  "Setting ignition timing": "اگنیشن ٹائمنگ",
  "Use of timing light": "ٹائمنگ لائٹ",
  "Checking of ignition system": "اگنیشن سسٹم چیک",
  "Components as ignition coil": "اگنیشن کوائل جیسے پرزے",
  "Condenser advance mechanism": "کنڈنسر ایڈوانس",
  "Servicing of spark plug": "سپارک پلگ سروس",
  "Checking & wiring up CDI system components": "CDI پرزوں کی وائرنگ اور چیک",
  "Trouble shooting their possible causes and remedies of ignition system":
    "اگنیشن سسٹم میں خرابی اور علاج",
  "Wiring up Head lamp circuit": " ہیڈ لیمپ سرکٹ وائرنگ",
  "Replacing fuses, switches and blubs": "فیوز، سوئچ اور بلب تبدیل",
  "Head lamp aiming": " ہیڈ لیمپ ایمنگ",
  "Wiring up Parking light circuit": "پارکنگ لائٹ سرکٹ",
  "Wiring up Indicator circuit & Hazard warning circuit": "انڈیکٹر اور خطرے کی وارننگ",
  "Wiring up Brake & backup light circuit": "بریک اور بیک اپ لائٹ",
  "Wiring up Door and roof light circuit": "دروازے اور چھت کی لائٹ",
  "Wiring up Horn circuit": "ہارن سرکٹ",
  "Wiring up wind shield wiper and washer circuit": "وائپر اور واشر سرکٹ",
  "Glow plug circuit and checking": "گلو پلگ سرکٹ",
  "Wiring up gauge circuits (Fuel, Temperature, oil pressure)": "گیج سرکٹ (فیول، درجہ حرارت، آئل)",
  "Parts identification and finding resistance of EFI components": "EFI پرزوں کی شناخت اور مزاحمت",
  "Removing & refitting of different sensors & vales used in EFI system":
    "EFI سینسرز اور والوز نکالنا/لگانا",
  "Dismantling, Servicing & Reassembling different sensors & valves of EFI System":
    "EFI سینسرز اور والوز سروس",
  "Removing, Servicing & refitting EFI fuel feed pump": "EFI فیول پمپ سروس",
  "Fault diagnosing in EFI System of different vehicles": "مختلف گاڑیوں میں EFI خرابی",
  "Removing inspecting & installation of AC compressor": "اے سی کمپریسر نکالنا/لگانا",
  "Servicing of Air conditioner": "اے سی سروس",
  "Gas charging of Air conditioner": "اے سی گیس چارجنگ",
  "Servicing of Vehicle Heater": "گاڑی ہیٹر سروس",
  "Parts identification of hybrid vehicle": "ہائبرڈ گاڑی پرزوں کی شناخت",
  "Identification of hybrid vehicle electronic controls": "ہائبرڈ الیکٹرانک کنٹرولز",
  "Parts identification of electric vehicle": "الیکٹرک گاڑی پرزوں کی شناخت",
};
