/** Display-only Urdu for Course 1 TOC; keys must match `app/api/course1/toc/route.ts` titles exactly. */
export const COURSE1_TOC_URDU: Record<string, string> = {
  "Basic Knowledge": "بنیادی علم",
  "Introduction to hand tools and their use": "ہینڈ ٹولز اور ان کے استعمال کا تعارف",
  "Measuring Introductions": "پیمائش کا تعارف",
  "Safety Precautions": "حفاظتی احتیاطیں",
  "Basic electricity": "بنیادی بجلی",
  "Bench work": "بینچ ورک",
  Filing: "ریفلنگ",
  Drilling: "ڈرلنگ",
  Sawing: "آری کاری",
  Fitting: "فٹنگ",
  Battery: "بیٹری",
  "Purpose of Battery(Theory)": "بیٹری کا مقصد (نظریہ)",
  "Principle of Battery(Theory)": "بیٹری کا اصول (نظریہ)",
  "Function of Battery(Theory)": "بیٹری کا کام (نظریہ)",
  "Construction of Battery(Theory)": "بیٹری کی ساخت (نظریہ)",
  "Starting System": "سٹارٹنگ سسٹم",
  "Purpose of Starting System(Theory)": "سٹارٹنگ سسٹم کا مقصد (نظریہ)",
  "Principle of Starting System(Theory)": "سٹارٹنگ سسٹم کا اصول (نظریہ)",
  "Function of Starting System(Theory)": "سٹارٹنگ سسٹم کا کام (نظریہ)",
  "Construction of Starting System (Theory)": "سٹارٹنگ سسٹم کی ساخت (نظریہ)",
  "Charging System": "چارجنگ سسٹم",
  "Purpose of Charging System (Theory)": "چارجنگ سسٹم کا مقصد (نظریہ)",
  "Principle of Charging System (Theory)": "چارجنگ سسٹم کا اصول (نظریہ)",
  "Function of Charging System (Theory)": "چارجنگ سسٹم کا کام (نظریہ)",
  "Construction of Charging System (Theory)": "چارجنگ سسٹم کی ساخت (نظریہ)",
  "Ignition System": "اگنیشن سسٹم",
  "Purpose of Ignition System (Theory)": "اگنیشن سسٹم کا مقصد (نظریہ)",
  "Principle of Ignition System (Theory)": "اگنیشن سسٹم کا اصول (نظریہ)",
  "Function of Ignition System (Theory)": "اگنیشن سسٹم کا کام (نظریہ)",
  "Construction of Ignition System (Theory)": "اگنیشن سسٹم کی ساخت (نظریہ)",
  "Types of Ignition System (Theory)": "اگنیشن سسٹم کی اقسام (نظریہ)",
  "Electrical and Electronic Devices": "بجلی اور الیکٹرانک آلات",
  "Function and Construction of Various Lights, switches, and fuses(Theory)":
    "مختلف لائٹیں، سوئچز اور فیوز کا کام اور ساخت (نظریہ)",
  "Horn, Wiper(Theory)": "ہارن، وائپر (نظریہ)",
  "Instrument panel lights and gauges(Theory)": "انسٹرومنٹ پینل لائٹیں اور میٹر (نظریہ)",
  Basic: "بنیادی",
  "Marking(Practical)": "مارکنگ (عملی)",
  "Threading(Practical)": "تھریڈنگ (عملی)",
  Measuring: "پیمائش",
  "Steel foot rule(Practical)": "سٹیل فٹ رول (عملی)",
  "Vernier caliper(Practical)": "ورنیئر کالیپر (عملی)",
  "Micrometer(Practical)": "مائیکرومیٹر (عملی)",
  "Dial gauge(Practical)": "ڈائل گیج (عملی)",
  "Feeler gauge(Practical)": "فیلر گیج (عملی)",
  "Basics of Electrician": "الیکٹریشن کی بنیادیں",
  "Introduction to Fasteners and materials(Practical)": "فاسٹنرز اور مواد کا تعارف (عملی)",
  "Demonstration with magnet Box(Practical)": "میگنیٹ باکس کے ساتھ مظاہرہ (عملی)",
  "Insulation removal, connecting wires tapping, sleeving, connecting thimbles(Practical)":
    "انسولیشن ہٹانا، تاروں کا کنکشن، ٹیپنگ، سلیو، تھمبل (عملی)",
  "Marking jumper wires and test lamp(Practical)": "جمپر تاریں اور ٹیسٹ لیمپ مارکنگ (عملی)",
  "Use of AVO meter, Use of Ampere and voltmeters in series and parallel circuit, checking voltage drop(Practical)":
    "AVO میٹر، سیریز و متوازی سرکٹ میں ایم میٹر و وولٹ میٹر، وولٹیج ڈراپ (عملی)",
  "Soldering Exercises: Fix Joint, eye Joint, and lap joint etc(Practical)":
    "سولڈرنگ: فکس، آئی اور لیپ جوائنٹ وغیرہ (عملی)",
  "Cautions for battery service (Practical)": "بیٹری سروس کی احتیاطیں (عملی)",
  "Preparation of Electrolyte(Battery) (Practical)": "الیکٹرولائٹ کی تیاری (بیٹری) (عملی)",
  "Checking Specific gravity(Battery)(Practical)": "مخصوص کثافت چیک کرنا (بیٹری) (عملی)",
  "Battery charging(Practical)": "بیٹری چارجنگ (عملی)",
  "Battery testing (Practical)": "بیٹری ٹیسٹنگ (عملی)",
  "Analysis and troubleshooting of Battery (Practical)": "بیٹری کا تجزیہ اور خرابی دور کرنا (عملی)",
  "Battery removing and replacing(Practical)": "بیٹری نکالنا اور لگانا (عملی)",
  "Care of Batteries in stock(Practical)": "اسٹاک میں بیٹری کی دیکھ بھال (عملی)",
  "Making terminals of battery(Practical)": "بیٹری ٹرمینل بنانا (عملی)",
  "Dry batteries(Practical)": "خشک بیٹریاں (عملی)",
  "Trouble shooting of Starting System (Practical)": "سٹارٹنگ سسٹم میں خرابی دور کرنا (عملی)",
  "Specifications of Starting System (Practical)": "سٹارٹنگ سسٹم کی تفصیلات (عملی)",
  "Starting system circuit on vehicle (Practical)": "گاڑی پر سٹارٹنگ سرکٹ (عملی)",
  "Checking, removal and installation of Starting System (Practical)":
    "سٹارٹنگ سسٹم چیک، نکالنا اور نصب کرنا (عملی)",
  "Disassembly of Starting System (Practical)": "سٹارٹنگ سسٹم کھولنا (عملی)",
  "Identification of parts of Starting System (Practical)": "سٹارٹنگ سسٹم کے پرزوں کی شناخت (عملی)",
  "Complete checking and inspection of all of Starting System (Practical)":
    "سٹارٹنگ سسٹم کی مکمل جانچ (عملی)",
  "components according to workshop manual of Starting System (Practical)":
    "ورکشاپ مینول کے مطابق پرزے (سٹارٹنگ سسٹم) (عملی)",
  "Assembling of starting motor (Practical)": "سٹارٹنگ موٹر اسمبلی (عملی)",
  "Performance tests of motor on test bench (Practical)": "ٹیسٹ بینچ پر موٹر کے ٹیسٹ (عملی)",
  "Charging system": "چارجنگ سسٹم",
  "Trouble shooting of Charging system (Practical)": "چارجنگ سسٹم میں خرابی دور کرنا (عملی)",
  "Specifications of Charging system (Practical)": "چارجنگ سسٹم کی تفصیلات (عملی)",
  "Charging system checking on vehicle (Practical)": "گاڑی پر چارجنگ سسٹم چیک (عملی)",
  "Fan belt adjusting of Charging system(Practical)": "فین بیلٹ ایڈجسٹمنٹ (چارجنگ) (عملی)",
  "Dismantling alternator (Practical)": "الٹرنیٹر کھولنا (عملی)",
  "Parts identification of Charging system(Practical)": "چارجنگ سسٹم پرزوں کی شناخت (عملی)",
  "Complete inspection of parts of Charging system according to workshop manual (Practical)":
    "چارجنگ پرزوں کی مکمل جانچ (ورکشاپ مینول) (عملی)",
  "Replacing carbon brush and bearing of Charging system (Practical)":
    "کاربن برش اور بیرنگ تبدیل کرنا (چارجنگ) (عملی)",
  "Diode testing of Charging system (Practical)": "ڈائیوڈ ٹیسٹ (چارجنگ سسٹم) (عملی)",
  "Assembling Alternator of Charging system (Practical)": "الٹرنیٹر اسمبلی (چارجنگ) (عملی)",
  "Double unit voltage Regulator of Charging system (Practical)": "ڈبل یونٹ وولٹیج ریگولیٹر (چارجنگ) (عملی)",
  "Identifying connections and making circuits of Charging system (Practical)":
    "کنکشنز کی شناخت اور سرکٹ بنانا (چارجنگ) (عملی)",
  "Installing IC regulators (Practical)": "IC ریگولیٹرز نصب کرنا (عملی)",
  "Trouble shooting of Ignition System (Practical)": "اگنیشن سسٹم میں خرابی دور کرنا (عملی)",
  "Spark test, inspection of high tension leads of Ignition System (Practical)":
    "سپارک ٹیسٹ، HT لیڈز کی جانچ (اگنیشن) (عملی)",
  "Spark plug fouling study (Practical)": "سپارک پلگ فاؤلنگ مطالعہ (عملی)",
  "Ignition coil checking (Practical)": "اگنیشن کوائل چیک (عملی)",
  "Ignition circuit checking (Practical)": "اگنیشن سرکٹ چیک (عملی)",
  "C.B Point replacing and gap adjusting (Practical)": "سی بی پوائنٹ تبدیلی اور گیپ (عملی)",
  "Setting Ignition timing of Ignition System (Practical)": "اگنیشن ٹائمنگ سیٹ کرنا (عملی)",
  "Checking air gap and pick up coil (Practical)": "ایئر گیپ اور پک اپ کوائل (عملی)",
  "Dismantling, checking and fitting distributor (Practical)": "ڈسٹریبیوٹر کھولنا، چیک اور فٹنگ (عملی)",
  "Fitting C.B point and condenser and starting coil on motorcycle (Practical)":
    "موٹرسائیکل پر سی بی پوائنٹ، کنڈنسر اور کوائل (عملی)",
  "Wiring Circuits on Wiring Board": "وائرنگ بورڈ پر سرکٹ",
  "Reading wiring diagrams(Practical)": "وائرنگ ڈایاگرام پڑھنا (عملی)",
  "Making thimble connectors(Practical)": "تھمبل کنیکٹر بنانا (عملی)",
  "Color codes of Wiring Circuits on Wiring Board(Practical)": "رنگ کوڈز (وائرنگ بورڈ) (عملی)",
  "Head lamp circuit with relay(Practical)": "ریلے کے ساتھ ہیڈ لیمپ سرکٹ (عملی)",
  "Aiming headlights(Practical)": " ہیڈ لائٹ ایمنگ (عملی)",
  "Parking brake circuit(Practical)": "پارکنگ بریک سرکٹ (عملی)",
  "Hazard warning circuit(Practical)": "خطرے کی وارننگ سرکٹ (عملی)",
  "Indicator circuit(Practical)": "انڈیکیٹر سرکٹ (عملی)",
  "Brake light circuit(Practical)": "بریک لائٹ سرکٹ (عملی)",
  "Reverse gear light circuits(Practical)": "ریورس گیئر لائٹ سرکٹ (عملی)",
  "Door and roof light circuit(Practical)": "دروازے اور چھت کی لائٹ سرکٹ (عملی)",
  "Horn circuit and adjustment(Practical)": "ہارن سرکٹ اور ایڈجسٹمنٹ (عملی)",
  "Fuel gauge circuit(Practical)": "فیول گیج سرکٹ (عملی)",
  "Oil pressure light circuit(Practical)": "آئل پریشر لائٹ سرکٹ (عملی)",
  "Trunk and hood light(Practical)": "ڈککی اور بونٹ لائٹ (عملی)",
  "Temperature gauge circuit(Practical)": "درجہ حرارت گیج سرکٹ (عملی)",
  "Brake fluid level light circuit(Practical)": "بریک فلویڈ لیول لائٹ (عملی)",
  "Power window circuit(Practical)": "پاور ونڈو سرکٹ (عملی)",
  "Wind shield and wiper motor circuit(Practical)": "وائڈ شیلڈ اور وائپر موٹر سرکٹ (عملی)",
  "Electric Fan circuit(Practical)": "الیکٹرک فین سرکٹ (عملی)",
  "Glow plug circuit(Practical)": "گلو پلگ سرکٹ (عملی)",
  "Electrical shut off valve circuit(Practical)": "شٹ آف والو سرکٹ (عملی)",
  "Radio and speaker circuit(Practical)": "ریڈیو اور اسپیکر سرکٹ (عملی)",
  "Car air conditioning and heating system wiring(Practical)": "اے سی اور ہیٹنگ وائرنگ (عملی)",
  "Work ethics": "کام کے اخلاقیات",
  "Work ethics (Practical)": "کام کے اخلاقیات (عملی)",
};
