/**
 * Display-only Urdu for Course 3 TOC titles (topic / subtopic / sub-subtopic).
 * Keys must match `title` fields in `app/api/course3/toc-data.ts` exactly.
 */
export const COURSE3_TOC_URDU: Record<string, string> = {
  "Workshop Practice": "ورکشاپ پریکٹس",
  "Safety precautions": "حفاظتی احتیاطیں",
  "Use of PPEs": "ذاتی حفاظتی سامان کا استعمال",
  "Causes of fire and types of fire": "آگ کی وجوہات اور اقسام",
  "Firefighting techniques": "آگ بجھانے کی تکنیکیں",
  "Occupational health and first aid": "صحتِ کار اور ابتدائی طبی امداد",
  "Introduction of trade tools, Machinery & Equipment": "تجارتی اوزار، مشینری اور آلات کا تعارف",
  "Different type of pliers and cutters": "پلائرز اور کٹرز کی اقسام",
  "Different types of screw drivers and wrenches": "سکرو ڈرائیورز اور رینچز کی اقسام",
  "Fasteners (Permanent and Temporary)": "فاسٹنرز (مستقل اور عارضی)",
  "Purpose and working of Fitting tools": "فٹنگ ٹولز کا مقصد اور کام",
  Multimeter: "ملٹی میٹر",
  "Hydro meter": "ہائیڈرو میٹر",
  "Teco meter": "ٹیکو میٹر",
  Oscilloscope: "آسیلوسکوپ",
  "Smoke tester": "سموک ٹیسٹر",
  "Feeler gauge": "فیلر گیج",
  "Spark plug cleaner": "سپارک پلگ کلینر",
  "Measuring and tools used in measuring": "پیمائش اور پیمائشی اوزار",
  "Measuring tape": "پیمائش ٹیپ",
  "Vertical venire": "ورٹیکل ورنیئر",
  "Head light Aim tester": " ہیڈ لائٹ ایم ٹیسٹر",
  Marking: "مارکنگ",
  "Cleaning tools": "صفائی کے اوزار",
  "Contact cleaner": "کنٹیکٹ کلینر",
  "Rust remover": "زنگ ہٹانے والا",
  "Hot water treatment": "گرم پانی کا علاج",
  "Carb cleaner": "کارب کلینر",
  "Multipurpose lubricant": "کثیر المقاصد مرہم تیل",
  "Fitting tools": "فٹنگ اوزار",
  "Internal combustion engine": "اندرونی احتراقی انجن",
  "Introduction to Internal combustion": "اندرونی احتراق کا تعارف",
  "Types of IC Engine": "آئی سی انجن کی اقسام",
  "Major Parts and components of IC engine": "آئی سی انجن کے اہم پرزے",
  "Systems of engine": "انجن کے نظام",
  "Difference between Spark ignition and Compression ignition engine":
    "سپارک اور کمپریشن اگنیشن انجن میں فرق",
  "Basic Electricity / Electronics": "بنیادی بجلی / الیکٹرانکس",
  "Application of electricity": "بجلی کا اطلاق",
  "Atomic structure of matter and electricity": "مادہ اور بجلی کی ذراتی ساخت",
  "Conductor, insulator, semi conductor": "چالک، موصل، نیم موصل",
  "Diodes and transistors": "ڈائیوڈز اور ٹرانزسٹرز",
  "Current, voltage and resistance": "کرنٹ، وولٹیج اور مزاحمت",
  "Ohm's law": "اوم کا قانون",
  "Magnet and magnetism": "میگنیٹ اور مقناطیسیت",
  "Left hand rule, electromagnet": "بائیں ہاتھ کا قانون، الیکٹرو میگنیٹ",
  "Components of electrical circuits": "بجلی کے سرکٹ کے پرزے",
  "Resistances and their coding, Relays, solenoid, printed circuits, circuit breaker, fuse, types of bulb and lamps, timers, terminals and switches":
    "مزاحمتیں اور کوڈنگ، ریلے، سولینائڈ، پرنٹڈ سرکٹ، بریکر، فیوز، بلب، ٹائمر، ٹرمینل، سوئچ",
  "Series and parallel circuits": "سیریز اور متوازی سرکٹ",
  "Combined series & Parallel circuits and their characteristics":
    "مشترکہ سیریز و متوازی سرکٹ اور خصوصیات",
  "Ampere meter and volt meter in circuits": "سرکٹ میں ایم میٹر اور وولٹ میٹر",
  "Integrated circuits, Capacitors, diodes, transistors": "انٹیگریٹڈ سرکٹ، کیپیسٹر، ڈائیوڈ، ٹرانزسٹر",
  "Interpretation of circuit diagram (EWD)": "سرکٹ ڈایاگرام (EWD) کی تفسیر",
  "Instrument cluster gauges and meters": "انسٹرومنٹ کلسٹر گیج اور میٹر",
  "Storage Battery": "اسٹوریج بیٹری",
  "Purpose and types of battery": "بیٹری کا مقصد اور اقسام",
  "Construction and identification of battery parts": "بیٹری پرزوں کی ساخت اور شناخت",
  "Electrolyte and its characteristics": "الیکٹرولائٹ اور خصوصیات",
  "Charging and discharging of battery": "چارج اور ڈسچارج",
  "Battery rating": "بیٹری ریٹنگ",
  "Usage of Battery charger (fast and slow charging)": "بیٹری چارجر (تیز/آہستہ چارج)",
  "Battery tester (reading magnet eye)": "بیٹری ٹیسٹر (میگنیٹ آئی)",
  "Use of jumper cables": "جمپر کیبلز کا استعمال",
  "Types of storage batteries": "اسٹوریج بیٹریوں کی اقسام",
  "Lead acid": "لیڈ ایسڈ",
  "Lithium ion": "لیتھیوم آئن",
  "Nickel Cadmium": "نکل کیڈمیئم",
  "Nickel-Metal Hydride": "نکل میٹل ہائیڈرائڈ",
  "Ignition System": "اگنیشن سسٹم",
  "Self-Starter": "سیلف سٹارٹر",
  "Self-starter & its components": "سیلف سٹارٹر اور اس کے پرزے",
  "Purpose and Principle of self-starter": "سیلف سٹارٹر کا مقصد اور اصول",
  "Construction and Function of self-starter": "سیلف سٹارٹر کی ساخت اور کام",
  "Neutral safety switch": "نیوٹرل سیفٹی سوئچ",
  "Remote switch": "ریموٹ سوئچ",
  "Applied brake start system": "بریک لاگو سٹارٹ سسٹم",
  Purpose: "مقصد",
  Principal: "اصول",
  "Types of ignition systems": "اگنیشن سسٹمز کی اقسام",
  "Magneto ignition system": "میگنیٹو اگنیشن",
  "Capacitor discharge ignition": "کیپیسٹر ڈسچارج اگنیشن",
  "Mechanically timed ignition": "میکینیکلی ٹائمڈ اگنیشن",
  "Single coil and Multi coil ignition": "سنگل اور ملٹی کوائل اگنیشن",
  "Cross fire (Spark waste) ignition": "کراس فائر اگنیشن",
  "Distributer type ignition system": "ڈسٹریبیوٹر ٹائپ اگنیشن",
  "Distributor less ignition": "ڈسٹریبیوٹر لیس اگنیشن",
  "Electronic Ignition and digital electronic ignition system": "الیکٹرانک اور ڈیجیٹل اگنیشن",
  "High energy ignition": "اعلیٰ توانائی اگنیشن",
  "Hall effect ignition": "ہال اثر اگنیشن",
  "Electronic Diesel fuel ignition (EDFI)": "الیکٹرانک ڈیزل فیول اگنیشن",
  "Construction and components of ignitions systems": "اگنیشن سسٹمز کی ساخت اور پرزے",
  "Spark plug and its types": "سپارک پلگ اور اقسام",
  "Glow plug and their function": "گلو پلگ اور ان کا کام",
  "Technical Drawing - I": "ٹیکنیکل ڈرائنگ - I",
  "Lines, lettering, dimensioning": "لائنیں، حروف، ڈائمینشننگ",
  "Identification of Electrical symbols": "بجلی کی علامات کی شناخت",
  "Series and parallel and combined circuits": "سیریز، متوازی اور مشترکہ سرکٹ",
  "Drawing of radiator fan circuit of car": "ریڈی ایٹر فین سرکٹ کی ڈرائنگ",
  "Drawing of wind screen wiper circuit of car": "وائڈ اسکرین وائپر سرکٹ کی ڈرائنگ",
  "Drawing of Magnet ignition (Circuit completion)": "میگنیٹ اگنیشن ڈرائنگ",
  "Drawing of Battery coil ignition (Circuit completion)": "بیٹری کوائل اگنیشن ڈرائنگ",
  "Drawing of Horn circuit": "ہارن سرکٹ کی ڈرائنگ",
  "Drawing of Head lamp and parking light circuit": " ہیڈ لیمپ اور پارکنگ لائٹ",
  "Drawing of Indicator circuit": "انڈیکیٹر سرکٹ کی ڈرائنگ",
  "Drawing of Wiper motor circuit": "وائپر موٹر سرکٹ کی ڈرائنگ",
  "Drawing of Door and roof light circuit": "دروازے اور چھت لائٹ کی ڈرائنگ",
  "Drawing of Charging circuit (with electronic regulator)": "چارجنگ سرکٹ (الیکٹرانک ریگولیٹر)",
  "Drawing of capacitor discharge ignition system of car": "CDI سسٹم کی ڈرائنگ",
  "Reading circuit diagrams of different cars from manual": "مینول سے سرکٹ ڈایاگرام پڑھنا",
  "Technical Mathematics - I": "ٹیکنیکل ریاضی - I",
  "Simple addition, subtraction": "سادہ جمع، تفریق",
  "Multiplication and division": "ضرب اور تقسیم",
  "Conversion of fraction to decimals": "کسر سے اعشاریہ",
  Percentage: "فیصد",
  "Square and under root": "مربع اور جذر",
  "Industrial tour": "صنعتی دورہ",
  "Functional English": "فنکشنل انگریزی",
  "Work Ethics": "کام کے اخلاقیات",
  "Wiring Circuits and Accessories": "وائرنگ سرکٹ اور لوازمات",
  "Charging Circuit / Voltage Regulators": "چارجنگ سرکٹ / وولٹیج ریگولیٹرز",
  "Charging Systems": "چارجنگ سسٹمز",
  "Construction and operation of double point voltage regulator":
    "ڈبل پوائنٹ وولٹیج ریگولیٹر کی ساخت اور عمل",
  "Type of voltage regulator": "ولٹیج ریگولیٹر کی قسم",
  "Electronic regulators": "الیکٹرانک ریگولیٹرز",
  Alternator: "الٹرنیٹر",
  "Purpose and Principle of Alternator": "الٹرنیٹر کا مقصد اور اصول",
  "Construction and Function of Alternator": "الٹرنیٹر کی ساخت اور کام",
  "Construction of circuits": "سرکٹ کی ساخت",
  "Horn circuit": "ہارن سرکٹ",
  "Head lamps circuit, other lights": " ہیڈ لیمپ اور دیگر لائٹس",
  "Directional signal circuit": "سمت اشارے کا سرکٹ",
  "Roof light circuit": "چھت کی لائٹ سرکٹ",
  "High low beam circuit": "ہائی لو بیم سرکٹ",
  "Wind shield wipers/washers circuit": "وائپر/واشر سرکٹ",
  "Power windows circuit": "پاور ونڈو سرکٹ",
  "Radiator fan circuit": "ریڈی ایٹر فین سرکٹ",
  "Cigrate lighter circuit": "سگریٹ لائٹر سرکٹ",
  "Multimedia control circuits": "ملٹی میڈیا کنٹرول سرکٹ",
  "Sun roof circuit": "سن روف سرکٹ",
  "Panoramic roof circuit": "پینورامک روف سرکٹ",
  "Auto light control circuits": "آٹو لائٹ کنٹرول",
  "Indicator light circuit": "انڈیکیٹر لائٹ سرکٹ",
  "Auto side view mirror close circuit": "سائیڈ شیشہ بند کرنے کا سرکٹ",
  "Fog light circuit": "فاگ لائٹ سرکٹ",
  "Parking light circuit": "پارکنگ لائٹ سرکٹ",
  "Electric power steering circuit": "الیکٹرک پاور اسٹیئرنگ",
  "Electronic power steering column control circuit (tilt and telescopic)":
    "الیکٹرانک اسٹیئرنگ کالم (ٹلٹ اور ٹیلی سکوپک)",
  "Electric seat adjustment circuit": "برقی سیٹ ایڈجسٹمنٹ",
  "Seat heating and ventilation circuit": "سیٹ ہیٹنگ اور وینٹیلیشن",
  "Seat massager circuit": "سیٹ مساج سرکٹ",
  "Service interval reset system": "سروس انٹرول ری سیٹ",
  "Sun wiser light circuit": "سن وائزر لائٹ",
  "Soft top convertible circuit": "سافٹ ٹاپ کنورٹیبل",
  "Hard top convertible circuit": "ہارڈ ٹاپ کنورٹیبل",
  "Door soft closing circuit": "دروازہ نرم بندش",
  "Electric trank lid open circuit": "برقی ڈکی کھولنے کا سرکٹ",
  "Electric fuel tank filling cap opener circuit": "فیول ٹینک کیپ اوپنر",
  "Heating and ventilating circuit": "گرم اور ہوا کاری",
  "Defogger circuit": "ڈی فوگر سرکٹ",
  "Side view mirror control circuit": "سائیڈ شیشہ کنٹرول سرکٹ",
  "Fuel system circuit": "فیول سسٹم سرکٹ",
  "Engine fan circuit": "انجن فین سرکٹ",
  "Interpretation of signs and symbols of instrument panel indicators":
    "انسٹرومنٹ پینل علامات کی تفسیر",
  "Electronically Controlled vehicle systems and sensors":
    "الیکٹرانک کنٹرول گاڑی کے نظام اور سینسر",
  "Purpose, construction and working of microprocessors and integrated circuit":
    "مائیکرو پروسیسر اور انٹیگریٹڈ سرکٹ",
  "EFI Components and their working (microprocessor, sensors and actuators)":
    "EFI پرزے اور ان کا کام",
  "Oxygen sensor": "آکسیجن سینسر",
  "Knock Sensor, variable valve lift (VVI) cam sensor (VVTI) actuator":
    "ناک سینسر، وی وی آئی، وی وی ٹی آئی",
  "Manifold Absolute Pressure (MAP) Sensor": "MAP سینسر",
  "Mass Air Flow (MAF) sensor": "MAF سینسر",
  "Throttle Position (TP) sensor": "TP سینسر",
  "Accelerator paddle position sensor": "ایکسلریٹر پیڈل پوزیشن سینسر",
  "Body accelerator sensor": "باڈی ایکسلریٹر سینسر",
  "Lateral Acceleration sensor": "لیٹرل ایکسلریشن سینسر",
  "Deceleration sensor": "ڈی ایکسلریشن سینسر",
  "Cam position sensor": "کیم پوزیشن سینسر",
  "Crank Position sensor": "کرینک پوزیشن سینسر",
  "Oil pressure sensor": "آئل پریشر سینسر",
  "Fuel level sensor": "فیول لیول سینسر",
  "Fuel pump (primary & secondary) sensor": "فیول پمپ سینسر",
  "Fuel injectors (actuators)": "فیول انجیکٹرز",
  "Electric Secondary air injection pump": "سیکنڈری ایئر انجیکشن پمپ",
  "Coolant temperature sensor": "کولنٹ درجہ حرارت سینسر",
  "Coolant level sensor": "کولنٹ لیول سینسر",
  "Electric coolant flow system": "برقی کولنٹ بہاؤ",
  "Electric coolant flow valve control (Thermostat)": "کولنٹ والو (تھرمواسٹٹ)",
  "Electronic Engine suction fan": "انجن سکشن فین",
  "Engine fan speed control module": "انجن فین رفتار ماڈیول",
  "Braking system": "بریکنگ سسٹم",
  "Brake fluid level sensor": "بریک فلویڈ لیول سینسر",
  "Brake fluid pressure sensor": "بریک فلویڈ پریشر سینسر",
  "Brake paddle travel sensor": "بریک پیڈل ٹریول سینسر",
  "Brake booster vacuum sensor": "بریک بوسٹر ویکیوم سینسر",
  "Electronic brake force distribution system": "الیکٹرانک بریک فورس ڈسٹری بیوشن",
  "Anti-lock brake (skidding) system": "اینٹی لاک بریک سسٹم",
  "Senstronic brake control system": "سینسٹرونک بریک کنٹرول",
  "Electric wedge brake system (EWB)": "برقی ویج بریک",
  "Electric Brake hold system": "برقی بریک ہولڈ",
  "Electric brake force distribution (EBD) system": "EBD سسٹم",
  "Brake assist (extra force apply) system": "بریک اسسٹ",
  "Regenerative brake system": "ریجنریٹو بریک",
  "Brake wear indication system": "بریک پہناؤ کی نشاندہی",
  "Catalytic convertor temperature sensor": "کیٹلیٹک کنورٹر درجہ حرارت",
  "Turbo boost pressure sensor": "ٹربو بوسٹ پریشر",
  "Intake Air Temperature (IAT) sensor": "IAT سینسر",
  "Rain sensor": "بارش سینسر",
  "Curb height control sensor": "کراب اونچائی کنٹرول",
  "Wheel Speed Sensor": " پہیے کی رفتار کا سینسر",
  "Fuel tank filling lock system": "فیول ٹینک لاک سسٹم",
  "Keyless entry system": "بغیر چابی داخلہ",
  "Keyless start (Push start) system": "پش سٹارٹ",
  "Basic of key programing": "چابی پروگرامنگ کی بنیاد",
  "Auto wiper system": "آٹو وائپر",
  "Auto light system": "آٹو لائٹ",
  "Rear window power sunshade": "پیچھے کھڑکی سن شیڈ",
  "Overhead control panel": "اوور ہیڈ کنٹرول",
  "Active distronic system": "ایکٹو ڈسٹرونک",
  "Interior illumination system": "اندرونی روشنی",
  "Night vision display system": "نائٹ ویژن ڈسپلے",
  "Safety and security": "حفاظت اور سیکیورٹی",
  "SRS air bag": "ایس آر ایس ائیر بیگ",
  "Electronic battery safety terminals": "بیٹری سیفٹی ٹرمینل",
  "Child lock system": "چائلڈ لاک",
  "Center locking system (Electric center locking, vacuum center locking)": "سینٹر لاکنگ",
  "Navigation system": "نیویگیشن",
  "Electric lid (Bonnet & Trunk) and door operating system": "بونٹ، ڈکی، دروازے برقی",
  "Tyre pressure monitoring system": "ٹائر پریشر مانیٹرنگ",
  "Radar system": "ریڈار",
  "Vehicle immobilizer system": "اموبلائزر",
  "Vehicle tracking system": "گاڑی ٹریکنگ",
  "Drive assist systems": "ڈرائیو اسسٹ",
  "Auto start, stop system": "آٹو سٹارٹ اسٹاپ",
  "Lane keeping assist system": "لین رکھنے میں مدد",
  "Electric stability control system": "استحکام کنٹرول",
  "Electric stability program system": "ESP",
  "Remote parking, auto parking system": "ریموٹ/آٹو پارکنگ",
  "Eco Idle drive system": "ایکو آئڈل",
  "Sports drive system": "اسپورٹس ڈرائیو",
  "Active speed limit control system": "رفتار حد کنٹرول",
  "Drive mode control system": "ڈرائیو موڈ",
  "Speed command system": "رفتار کمانڈ",
  "Auto pilot system": "آٹو پائلٹ",
  "Triptronic system": "ٹرپٹرونک",
  "Active blind spot assist system": "بائنڈ سپاٹ اسسٹ",
  "Active steering system in sleep mode": "سلیپ موڈ اسٹیئرنگ",
  "Active lane change system": "لین تبدیلی اسسٹ",
  "Active steering system in lane control": "لین کنٹرول اسٹیئرنگ",
  "Automatic transmission controls": "آٹو ٹرانسمیشن کنٹرول",
  "Traction control system": "ٹریکشن کنٹرول",
  "Dynamic drive control system": "ڈائنامک ڈرائیو",
  "Adaptive dynamic drive control system": "ایڈاپٹو ڈائنامک",
  "Cruise control system": "کروز کنٹرول",
  "Skid control system": "سکڈ کنٹرول",
  "Parktronic system": "پارکٹرونک",
  "Electronic control of Manual transmission": "مینوئل ٹرانسمیشن الیکٹرانک",
  "Automatic transmission system": "آٹو ٹرانسمیشن",
  "CVT system": "CVT",
  "Dual clutch transmission system, Hydromantic transmission system, Transfer case system":
    "ڈوئل کلچ، ہائیڈرومینٹک، ٹرانسفر کیس",
  "4x4 drives, X Drive electric control system": "4x4 اور ایکس ڈرائیو",
  "Suspension system": "معطلی کا نظام",
  "Electronic drive mode (soft hard drive) controlled circuits in Suspension system":
    "سسپنشن میں ڈرائیو موڈ سرکٹ",
  "Pneumatic suspension system": "نیومیٹک سسپنشن",
  "Hydraulic suspension system": "ہائیڈرولک سسپنشن",
  "Dynamic stability control system": "ڈائنامک استحکام",
  "Hybrid vehicles": "ہائبرڈ گاڑیاں",
  "Types of hybrid system": "ہائبرڈ کی اقسام",
  "Mild parallel hybrid": "مایلڈ پیرلل ہائبرڈ",
  "Power-split or series-parallel hybrid": "پاور سپلٹ/سیریز پیرلل",
  "Series hybrid": "سیریز ہائبرڈ",
  "Plug-in hybrid electric vehicle (PHEV)": "پلگ ان ہائبرڈ",
  "Introduction to alternative fuel and emission less vehicles":
    "متبادل ایندھن اور کم اخراج گاڑیاں",
  "Compressed Natural Gas (CNG)": "CNG",
  "Liquefied Natural Gas (LNG)": "LNG",
  Hydrogen: "ہائیڈروجن",
  "Ethanol Fuel": "ایتھنول ایندھن",
  "Electric vehicles & Solar energy cars": "الیکٹرک اور سولر گاڑیاں",
  "Usage of Diagnostic scanner": "ڈائگنوستک سکینر کا استعمال",
  "Fault diagnosing and interpreting codes": "خرابی اور کوڈز کی تفسیر",
  "Electrical circuit checking and repairing": "سرکٹ چیک اور مرمت",
  "Trouble shooting of vehicle electrical system": "بجلی کے نظام میں خرابی دور کرنا",
  "Heating, Ventilating and Air Conditioning system": "گرم، ہوا کاری اور اے سی",
  "Cooling system": "کولنگ سسٹم",
  "Basic Function of HVAC system": "HVAC کا بنیادی کام",
  "Components of cooling system": "کولنگ پرزے",
  "AC cooling fan": "اے سی کولنگ فین",
  "AC blower control regulator": "اے سی بلوئر ریگولیٹر",
  "Flap control motor": "فلیپ موٹر",
  Condenser: "کنڈنسر",
  "Expansion valve": "توسیعی والو",
  "Evaporator coil": "ایواپوریٹر کوائل",
  Thermostat: "تھرمواسٹٹ",
  "AC and heater circuits": "اے سی اور ہیٹر سرکٹ",
  "Construction and types of compressor": "کمپریسر کی ساخت اور اقسام",
  "Types of refrigerants": "ریفریجرنٹ کی اقسام",
  "Humidity sensor": "نمی سینسر",
  "Internal temperature sensor": "اندرونی درجہ حرارت سینسر",
  "Evaporator temperature sensor": "ایواپوریٹر درجہ حرارت",
  "Refrigerant temperature sensor": "ریفریجرنٹ درجہ حرارت",
  "Refrigerant pressure sensor": "ریفریجرنٹ پریشر",
  "Air control flap motors": "ہوا کنٹرول فلیپ موٹر",
  "Heating system": "گرم کرنے کا نظام",
  "Components of heating system": "ھیٹر کے پرزے",
  "Working of heating system": "ھیٹر کا کام",
  "Auto temperature control of vehicle": "خودکار درجہ حرارت",
  "Seat heating and cooling system": "سیٹ گرمی اور ٹھنڈک",
  "Cool box (fridge) system": "کول باکس (فریج)",
  "Automatic climate control system": "خودکار موسم کنٹرول",
  "Side view mirror heating system": "سائیڈ شیشہ ہیٹنگ",
  "Wind screen and rear screen heating system": "وائڈ/ریئر اسکرین ہیٹنگ",
  "Steering heating system": "اسٹیئرنگ ہیٹنگ",
  "Technical Drawing - II": "ٹیکنیکل ڈرائنگ - II",
  "Drawing of auto start system of car": "آٹو سٹارٹ کی ڈرائنگ",
  "Drawing of engine control unit of car": "ECU کی ڈرائنگ",
  "Drawing of security system of car": "سیکیورٹی کی ڈرائنگ",
  "Completing car wiring diagram": "وائرنگ ڈایاگرام مکمل کرنا",
  "Drawing of key type & keyless entry system of car": "چابی/کی لیس داخلہ ڈرائنگ",
  "Drawing of auto door lock system of car": "آٹو ڈور لاک ڈرائنگ",
  "Drawing of Anti-lock braking circuit": "اینٹی لاک بریک سرکٹ",
  "Drawing of Air conditioning circuit": "اے سی سرکٹ کی ڈرائنگ",
  "Technical Mathematics - II": "ٹیکنیکل ریاضی - II",
  "Area and circumference of circle, triangle, square, rectangle, trapezium and compound shapes":
    "دائرہ، مثلث، مربع، مستطیل، ذوزنقہ اور مرکب شکلیں",
  "Ohm's Law, drop voltage in Series and parallel circuit": "اوم کا قانون، وولٹیج ڈراپ",
  "Electrical work, electrical power and battery capacity": "بجلی کا کام، طاقت، بیٹری گنجائش",
};
